In [4]:
# Import dependencies

import numpy as np
import pandas as pd
import matplotlib as plt

In [6]:
# Add CSV
df = pd.read_csv("mental_health_and_technology_usage_2024.csv")
df

,User_ID,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Mental_Health_Status,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact,Online_Support_Usage
0,USER-00001,23,Female,6.57,6.00,0.68,12.36,Good,Low,8.01,6.71,No,Negative,Yes
1,USER-00002,21,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive,No
2,USER-00003,51,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative,No
3,USER-00004,25,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative,Yes
4,USER-00005,53,Male,1.20,0.56,0.29,12.63,Good,Low,5.55,4.00,No,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,USER-09996,42,Male,7.05,0.41,0.53,13.90,Good,Medium,7.37,5.02,Yes,Neutral,No
9996,USER-09997,31,Other,3.12,6.79,0.80,1.17,Fair,Medium,8.92,9.78,No,Neutral,Yes
9997,USER-09998,23,Male,4.38,3.98,0.52,7.81,Poor,High,7.59,2.99,No,Positive,No
9998,USER-09999,38,Male,4.44,1.48,3.28,13.95,Poor,Medium,7.26,2.24,Yes,Neutral,Yes
9999,USER-10000,41,Male,2.50,4.80,0.25,8.82,Fair,Low,4.62,5.09,Yes,Positive,Yes

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   User_ID                   10000 non-null  object
 1   Age                       10000 non-null  int64
 2   Gender                    10000 non-null  object
 3   Technology_Usage_Hours    10000 non-null  float64
 4   Social_Media_Usage_Hours  10000 non-null  float64
 5   Gaming_Hours              10000 non-null  float64
 6   Screen_Time_Hours         10000 non-null  float64
 7   Mental_Health_Status      10000 non-null  object
 8   Stress_Level              10000 non-null  object
 9   Sleep_Hours               10000 non-null  float64
 10  Physical_Activity_Hours   10000 non-null  float64
 11  Support_Systems_Access    10000 non-null  object
 12  Work_Environment_Impact   10000 non-null  object
 13  Online_Support_Usage      10000 non-null  object
dtypes: float64(6), int64(1), object(7)
memory usage: 1.1+ MB

In [ ]:
#add first graph